apiVersion: apps/v1
kind: Deployment
metadata:
  name: insurance-application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: insurance-application
  template:
    metadata:
      labels:
        app: insurance-application
    spec:
      containers:
        - name: insurance-application
          image: nikitaram2799/insurance:latest
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: insurance-application-service #The name of the Kubernetes Service to be created in the Kubernetes cluster
spec:
  selector:
    app: insurance-application 
  type: LoadBalancer #Type of the Kubernetes Service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8081
