apiVersion: apps/v1
kind: Deployment
metadata:
  name: insurance_application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: insurance_application
  template:
    metadata:
      labels:
        app: insurance_application
    spec:
      containers:
        - name: insurance_application
          image: nikitaram2799/insurance:latest
          ports:
            - containerPort: 8081
