apiVersion: v1
kind: Service
metadata:
  name: insurance_application-service #The name of the Kubernetes Service to be created in the Kubernetes cluster
spec:
  selector:
    app: insurance_application 
  type: LoadBalancer #Type of the Kubernetes Service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8081
